project:
  type: website
  preview:
    port: 4200

website:
  title: "Menino's Lab"
  description: "Menino's personal blog space to learn and share knowledge"
  open-graph: true
  page-navigation: true
  page-footer: 
    right: "Website made with [Quarto](https://quarto.org/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."

  site-url: https://blog.fmenino.dev/

  navbar:
    left: 
      - text: Posts
        href: posts/index.qmd

    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/M3nin0
      - icon: linkedin
        href: https://linkedin.com/in/fmenino
      - icon: rss
        href: index.xml

  search: 
    location: navbar
    type: overlay

  comments: 
    giscus: 
      repo: m3nin0-labs/blog

format:
  html:
    theme: 
      light:
        - simplex
        - style/theme.scss
      dark:
        - darkly
        - style/theme.scss
    css: style/global.css
