[project]
name = "blog-environment"
version = "0.1.0"
description = "Blog environment"
authors = ["Felipe Carlos <efelipecarlos@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
quarto = ">=1.4.550,<1.5"
jupyter = ">=1.1.1,<2"
