---
title: "It's alive!"
author: "Felipe Carlos"
date: "2024-05-14"
categories: [history]
---

Sharing open data, tools, and knowledge is a transformative action for those who share and those who use the shared content. This logic creates a circular economy, where what is generated and shared by one is used by others as a basis for more productions, which will also be shared at some point.

This circular logic generates new and more robust tools, knowledge, and data. This is because the problems and limitations of an initial version of these elements are progressively reduced through their use and improvements over time.

This concept is spread in various contexts, such as software, scientific, and productive (e.g., agriculture and livestock). For example, in the software context, several tools, such as Linux and programming languages like Python and R, are shared as open-source, helping thousands of people daily. In the scientific context, the openness of data and tools beyond the methodological description in articles has shown the ability to accelerate scientific production.

Bringing these concepts to my reality as a software developer, such sharing practices have been part of my life since the first command line I wrote in Shell. I learned a lot with open forums and wikis, and of course, I used many open tools.

So, to keep the circular economy running in my context, I always try to share what I am learning. An example of this is the [DataAt](https://github.com/dataAt) initiative, in which I was a collaborator from 2017 to 2022, where together with friends, we produced materials on [Data Science](https://dataat.github.io/introducao-analise-de-dados/), [Spatial Data Science](https://dataat.github.io/introducao-analise-de-dados-espaciais/introdu%C3%A7%C3%A3o.html), and [Docker](https://dataat.github.io/introducao-docker/). Our last release was the [Introduction to Machine Learning](https://dataat.github.io/introducao-ao-machine-learning/) book.

Now, to keep sharing and motivated by my distinguished friend [Carlos Neto](https://carlosneto.dev/), I created this blog to share my experiments and experiences in managing and processing geospatial data (e.g., data cubes, geospatial metadata, land use, and land cover maps).

See you soon 👋🏾
